### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by rosettakrb** [nateyolles/aem-developer-chrome#15] opened 2015-02-06 14:30 UTC
Hi,

This extension no longer works.  when i click the button in the Chrome toolbar, it looks like it's been clicked, but the menu that used to appear doesn't show.

I recently had to uninstall and re-install Chrome, but i also did the same to this plugins.

**Comment by nateyolles** [comment] 2015-02-06 23:22
Thank for contributing to the project by submitting an issue. I have not experienced this issue nor has it been reported by anyone else. Please keep me updated if this issue persists or if you have any new information to add.

**Comment by nateyolles** [comment] 2015-05-21 07:20
Unable to reproduce and no further reports in almost 4 months. Closing ticket.

**Closed by nateyolles** 2015-05-21 07:20 UTC
